### PR TITLE
fix zig-zag decoding

### LINKED ISSUE #7: Rendering on web looks broken
This is the example app, viewed in chrome:

Screenshot 2022-01-02 at 12 06 28

And here viewed in safari:

Screenshot 2022-01-02 at 12 10 31

Maybe this is related to differences in handling of floating-point numbers between the Dart VM and JS engines.

### PR DESCRIPTION
**Pull request by blaugold**
To make bitwise operations platform independent the
[docs](https://dart.dev/guides/language/numbers#what-should-you-do)
recommend coercing to signed 32 bit integers.

Fixes #7

### CODE REVIEW

File: lib/src/model/geometry_decoding.dart [hunk 1]
```diff
@@ -24,7 +24,7 @@ _Command _decodeCommand(int command) {
 int _decodeCommandLength(int command) => command >> 3;
 
 @pragma('vm:prefer-inline')
-int _decodeZigZag(int value) => (value >> 1) ^ -(value & 1);
+int _decodeZigZag(int value) => ((value >> 1) ^ -(value & 1)).toSigned(32);
```
Comment (greensopinion) [inline lib/src/model/geometry_decoding.dart:27]: Thanks for the PR, this looks fantastic.

The [vector tile spec 2.1](https://github.com/mapbox/vector-tile-spec/tree/master/2.1/) indicates: 

> A geometry is encoded as a sequence of 32 bit unsigned integers

Any concern with using signed 32-bit integers? Wondering if it might affect the results.

Also curious as to why `toSigned(32)` is applied after the bitwise operations, rather than before. Should we be doing something like this instead?

```dart
int _decodeZigZag(int value) {
  final value32 = value.toSigned(32)
  return (value32 >> 1) ^ -(value32 & 1);
}
```

Comment (blaugold) [reply lib/src/model/geometry_decoding.dart:27]: The decoded parameter values fit into signed 32-bit integers:

> Parameter values greater than pow(2,31) - 1 or less than -1 * (pow(2,31) - 1) are not supported.

The results of bitwise operations are different between native and web because of the different underlying representations. I'm not sure how this works exactly, but for 32-bit chunks we can get consistent results everywhere by interpreting the results of bit-wise operations as signed 32-bit numbers.

> For bit manipulation, consider explicitly operating on 32-bit chunks, which are consistent on all platforms. To force a signed interpretation of a 32-bit chunk, use int.toSigned(32).

**Comment by greensopinion** [comment]
Screenshot with this and #52 in a web browser 🎉 

Screen Shot 2022-07-27 at 6 15 48 PM

Still appears to work fine with this and [[vector_map_tiles](https://pub.dev/packages/vector_map_tiles)](https://github.com/greensopinion/flutter-vector-map-tiles) (mac application tested)

Screen Shot 2022-07-27 at 6 18 36 PM
